version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.19.1
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        managementApiSecret: pollposition123
        databases:
          default:
            connector: postgres
            host: host.docker.internal
            port: '5432'
            database: poll-position
            user: postgres
            password: postgres
            migrations: true
            rawAccess: true
